services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - mini-platform-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      start_period: 5s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data
    networks:
      - mini-platform-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  mini-platform-network:

