name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
            docker build -t ghcr.io/ojasik/mini-platform:${{ github.sha }} . 
            docker push ghcr.io/ojasik/mini-platform:${{ github.sha }} 

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Kubernetes
        run: |
            kubectl set image deployment/mini-platform-api mini-platform-api=ghcr.io/ojasik/mini-platform:${{ github.sha }}

            kubectl rollout status deployment/mini-platform-api